import Head from "next/head";
import Image from "next/image";
import Meta from "../components/seo/Meta";
import { prefix } from "../utils/prefix";

export default function Home() {
  return (
    <>
      {/* <Meta
        title="How are you today"
        description="Generated by create next app"
      /> */}
      <Head>
        <title>How are you today</title>
        <meta name="description" content="what's you story" />
        <link rel="icon" href={`${prefix}/favicon.ico`} />
      </Head>

      <main>
        <h1>Hello Beautiful world!</h1>
      </main>
    </>
  );
}
